// ASTRIA — toutes les chaînes visibles par le joueur (français).
// Changer de langue = remplacer ce module par un autre fichier de données.
export const STR = {
  title: "ASTRIA",
  subtitle: "Les Éclats du Ciel Brisé",

  nav_home: "Accueil",
  nav_heroes: "Héros",
  nav_campaign: "Campagne",
  nav_summon: "Invocation",
  nav_quests: "Quêtes",

  gold: "Or",
  diamonds: "Diamants",
  scrolls: "Sceaux",

  welcome_title: "Bienvenue, Astrelien !",
  welcome_body: "Il y a mille ans, le Cœur Céleste a explosé et la Brume dévore les îles flottantes d'Astria. Vous portez la Boussole d'Aube : ralliez les Éveillés, formez votre équipe et rallumez le ciel, île par île. Vos héros combattent même quand vous êtes absent — revenez récolter votre butin !",
  welcome_cta: "Commencer l'aventure",
  gift_title: "Cadeau de départ",
  gift_body: "Kaelis, la Lame du Zénith rejoint votre équipe ! Vous recevez aussi 10 Sceaux pour votre première invocation ×10.",
  gift_cta: "Merci !",

  afk_title: "Butin de la Boussole",
  afk_desc: "Vos héros ont combattu pendant votre absence.",
  afk_duration: "Temps d'absence",
  afk_cap: "(plafond 12 h)",
  afk_claim: "Réclamer",
  afk_instant: "Butin instantané (2 h)",
  afk_instant_used: "Butin instantané utilisé aujourd'hui",
  afk_rate: "Gains actuels",
  afk_per_min: "/ min",
  afk_empty: "Le coffre se remplit… revenez un peu plus tard !",

  team_title: "Équipe (max 5)",
  team_edit: "Modifier l'équipe",
  team_power: "Puissance",
  team_full: "Équipe complète — retirez d'abord un héros.",

  heroes_title: "Mes Éveillés",
  heroes_owned: "possédés",
  hero_level: "Niv.",
  hero_power: "Puissance",
  hero_upgrade: "Améliorer",
  hero_ascend: "Ascension",
  hero_ascend_need: "doublons requis",
  hero_max: "MAX",
  hero_in_team: "Dans l'équipe",
  hero_add_team: "Ajouter à l'équipe",
  hero_remove_team: "Retirer de l'équipe",
  hero_copies: "Doublons",
  hero_not_owned: "Non recruté",
  hero_stats_hp: "PV",
  hero_stats_atk: "ATQ",
  hero_stats_def: "DÉF",
  hero_stats_spd: "VIT",
  hero_ult: "Ultime",

  campaign_title: "La Reconquête",
  campaign_chapter: "Chapitre",
  campaign_stage: "Niveau",
  campaign_boss: "BOSS",
  campaign_fight: "Combattre",
  campaign_reco: "Puissance conseillée",
  campaign_first_clear: "Première victoire",
  campaign_cleared: "Île reconquise !",
  campaign_locked: "Terminez le niveau précédent",

  intro_vs: "VS",
  wave: "Vague",
  chef: "Chef",
  intro_ready: "En position !",

  battle_victory: "VICTOIRE !",
  battle_defeat: "Défaite…",
  battle_defeat_tip: "Améliorez vos héros, ajustez l'équipe ou réclamez votre butin AFK avant de retenter.",
  battle_rewards: "Récompenses",
  battle_continue: "Continuer",
  battle_retry: "Réessayer",
  battle_speed: "Vitesse",
  battle_skip_wait: "Combat en cours…",
  battle_vs: "VS",
  battle_echo: "Écho de",
  battle_timeout: "Temps écoulé — la Brume se referme.",

  summon_title: "Autel d'Invocation",
  summon_one: "Invoquer ×1",
  summon_ten: "Invoquer ×10",
  summon_cost_1: "300 diamants ou 1 sceau",
  summon_cost_10: "2 700 diamants ou 10 sceaux",
  summon_pity: "Légendaire garanti dans",
  summon_pity_myth: "Nhyx (Mythique) garanti dans",
  summon_pulls: "tirages",
  summon_new: "NOUVEAU !",
  summon_dupe: "Doublon → Ascension",
  summon_not_enough: "Diamants ou sceaux insuffisants. Terminez des quêtes et des niveaux de campagne !",
  summon_again: "Invoquer encore",
  summon_close: "Fermer",
  summon_rates: "Taux : Éveillé 58 % · Astral 33 % · Légendaire 8,4 % · Mythique 0,6 % — Légendaire garanti tous les 30 tirages, Nhyx garanti au 80e tirage.",

  quests_title: "Quêtes du jour",
  quests_reset: "Réinitialisation quotidienne à minuit",
  quest_claim: "Réclamer",
  quest_claimed: "Réclamé",
  quest_win3: "Gagner 3 combats de campagne",
  quest_summon1: "Faire 1 invocation",
  quest_afk1: "Réclamer le butin AFK",
  quest_upgrade3: "Améliorer 3 fois un héros",
  login_title: "Connexion — 7 jours",
  login_day: "Jour",
  login_claim: "Réclamer le jour",
  login_done: "Revenez demain pour la suite !",

  factions_title: "Boucle des factions",
  factions_hint: "Solacia > Verdaine > Karvok > Nérisse > Solacia · Nyxara ⇄ Lucens (+25 % de dégâts sur la faction dominée)",

  toast_gold: "or",
  toast_diamonds: "diamants",
  toast_scrolls: "sceaux",
  toast_upgraded: "amélioré au niveau",
  toast_ascended: "Ascension !",
  toast_saved: "Progression sauvegardée",
  toast_team_saved: "Équipe enregistrée",

  install_hint: "Astuce : ajoutez ASTRIA à votre écran d'accueil pour y jouer comme une appli.",

  cls_tank: "Rempart", cls_warrior: "Lame", cls_assassin: "Ombre",
  cls_archer: "Arc", cls_mage: "Arcane", cls_support: "Aube",

  fac_solacia: "Solacia", fac_verdaine: "Verdaine", fac_karvok: "Karvok",
  fac_nerisse: "Nérisse", fac_nyxara: "Nyxara", fac_lucens: "Lucens",

  rar_eveille: "Éveillé", rar_astral: "Astral", rar_legendaire: "Légendaire", rar_mythique: "Mythique",

  ch_names: ["Le Zénith Doré", "La Sylve Suspendue", "Les Forges d'Écume", "L'Archipel des Marées", "Le Voile Ombral"],
  ch_endless: "La Cicatrice",
};
